version: '3.8'

services:
  server:
    build: .
    restart: always
    command: >
      sh -c "cd app &&
             alembic upgrade head &&
             cd .. &&
             uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - ./:/app/
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - menu_network

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 1s
      timeout: 3s
      retries: 10
    networks:
      - menu_network

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - menu_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 10

volumes:
    postgres_data:

networks:
  menu_network:
    name: menu_network
    external: false
